[dashboard]
dashboard-160 ansible_host=192.168.1.160 ansible_user=ubuntu

[kvm_hosts]
kvm-host-153 ansible_host=192.168.1.153 ansible_user=ubuntu
kvm-host-154 ansible_host=192.168.1.154 ansible_user=ubuntu
